### ISSUE TITLE
tagstring argument for add method

### ISSUE THREAD

**Issue by nilesjohnson** [sethjohnson1/conflist5#31]
There is code in the New Announcement button to set the tags for a new announcement based on the current url.  In the new version, this is ignored, but we could re-enable it.

**Comment by sethjohnson1** [comment]
Ah, OK... makes sense. Just a few more shenanigans with the `tagarray` 😀 - check it out now!

**Comment by nilesjohnson** [comment]
merged to main and pulled to production; works fine!
